version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:80"
    volumes:
      - ./backend:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./frontend/react-workouts
    ports:
      - "3000:80"
    depends_on:
      - backend
